"""align users with keycloak identity

Revision ID: 338fd23d1b9b
Revises: eb6aa3b58ddc
Create Date: 2026-08-15 10:23:17.596640

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '338fd23d1b9b'
down_revision: str | Sequence[str] | None = 'eb6aa3b58ddc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "users",
        sa.Column(
            "keycloak_user_id",
            sa.Uuid(),
            nullable=True,
        ),
    )

    op.add_column(
        "users",
        sa.Column(
            "display_name",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.drop_column(
        "users",
        "password_hash",
    )

    # No application users exist yet, so the new identity
    # column can safely become mandatory.
    op.alter_column(
        "users",
        "keycloak_user_id",
        existing_type=sa.Uuid(),
        nullable=False,
    )

    op.create_index(
        op.f("ix_users_keycloak_user_id"),
        "users",
        ["keycloak_user_id"],
        unique=True,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_keycloak_user_id'), table_name='users')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'keycloak_user_id')
    # ### end Alembic commands ###
