"""refine verse content model

Revision ID: 8409533e0e41
Revises: e7adb7dbae7e
Create Date: 2026-08-15 20:23:19.168979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8409533e0e41'
down_revision: Union[str, Sequence[str], None] = 'e7adb7dbae7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verse_contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verse_id', sa.Uuid(), nullable=False),
    sa.Column('edition_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verse_id'], ['verses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verse_id', 'edition_id', 'content_type', 'language', name='uq_verse_content_variant')
    )
    op.create_index(op.f('ix_verse_contents_content_type'), 'verse_contents', ['content_type'], unique=False)
    op.create_index(op.f('ix_verse_contents_edition_id'), 'verse_contents', ['edition_id'], unique=False)
    op.create_index(op.f('ix_verse_contents_verse_id'), 'verse_contents', ['verse_id'], unique=False)
    op.drop_index(op.f('ix_verses_edition_id'), table_name='verses')
    op.drop_constraint(op.f('verses_edition_id_fkey'), 'verses', type_='foreignkey')
    op.drop_column('verses', 'edition_id')
    op.drop_column('verses', 'source_reference')
    op.drop_column('verses', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verses', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('verses', sa.Column('source_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('verses', sa.Column('edition_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('verses_edition_id_fkey'), 'verses', 'editions', ['edition_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_verses_edition_id'), 'verses', ['edition_id'], unique=False)
    op.drop_index(op.f('ix_verse_contents_verse_id'), table_name='verse_contents')
    op.drop_index(op.f('ix_verse_contents_edition_id'), table_name='verse_contents')
    op.drop_index(op.f('ix_verse_contents_content_type'), table_name='verse_contents')
    op.drop_table('verse_contents')
    # ### end Alembic commands ###
